name: Sync labels
on:
  push:
    paths:
      - './labels.*'
  workflow_dispatch:

jobs:
  labels:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EndBug/label-sync@v2
        with:
          config-file: ./labels.yml
